#!/usr/bin/env node
// Generate index.ts — the public barrel re-exporting every component in
// components/. GENERATED rather than hand-maintained: the catalog is
// ~539 components and grows, and this barrel is ng-packagr's own
// `lib.entryFile` (see ng-package.json) -- the real published API
// surface, not a legacy artifact. It had no generator at all until
// 2026-09-26 (tasks.md P8-T16): the last 48 national-identifier
// components (both 2026-09-22 growth rounds) landed real -input/-view
// implementations but were never added here, so the published
// @lilydesignsystem/angular-headless package silently exported none of
// them, while every sibling catalog (svelte/react/vue/web-components)
// already regenerates its own barrel via its own build.mjs.
//
// Exported names are DISCOVERED from each source file rather than
// assumed to be exactly the file's own name: almost every component
// exports exactly one class matching its filename, but at least one
// (Listbox.ts) also exports a type (ListboxNavigation) that consumers
// need too. Guessing a single name per file would silently drop that.

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const componentsDir = path.join(root, "components");

/** Source files that are components -- not tests, not Storybook stories. */
function isComponentSource(name) {
  if (!name.endsWith(".ts")) return false;
  if (name.endsWith(".spec.ts")) return false;
  if (name.includes(".stories.")) return false;
  return true;
}

const files = fs.readdirSync(componentsDir).filter(isComponentSource).sort();

if (files.length === 0) {
  throw new Error(`No component sources found in ${componentsDir}.`);
}

const lines = [];
const seen = new Map();

for (const file of files) {
  const name = file.slice(0, -".ts".length);
  const source = fs.readFileSync(path.join(componentsDir, file), "utf8");
  const exported = [
    ...source.matchAll(/^export (?:class|interface|type) ([A-Za-z0-9_]+)/gm),
  ].map((match) => match[1]);

  if (exported.length === 0) {
    throw new Error(`${file}: no top-level "export class/interface/type" found.`);
  }

  lines.push(`export { ${exported.join(", ")} } from "./components/${name}";`);

  // A duplicated export name makes the barrel ambiguous, and bundlers
  // resolve that by dropping one side silently. Fail loudly instead.
  for (const name of exported) {
    if (seen.has(name)) {
      throw new Error(
        `Duplicate export "${name}": declared by both ${seen.get(name)} and ${file}.`,
      );
    }
    seen.set(name, file);
  }
}

const barrel =
  "// Lily Design System - Angular Headless\n" +
  "// Barrel re-export for every component in the catalog.\n" +
  "// Generated by generate-index.mjs -- do not edit by hand.\n\n" +
  lines.join("\n") +
  "\n";

fs.writeFileSync(path.join(root, "index.ts"), barrel);
console.log(`generated index.ts (${files.length} components, ${seen.size} exports)`);
